// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "goku":return img`
..................................
..................................
..................................
..................................
.....................fffff........
...................fffff..........
..................fffff...........
.................ffffff...........
.................fffff..ffff......
...............fffffff.fffffff....
...............ffffffffffffffff...
...............fffffffffffffffff..
...............ffffffffffffffffff.
.............fffffffffffffffffffff
............ffffffffffffffffff....
...........fffffffffffffffff......
...........ffffffffffffffff.......
.......ffffffffffffffffffffff.....
.........ffffffffffdfffffffffff...
......fffffffffdfffdddffffffffff..
...ffffffffffffffffddddffffff.....
.....fffffffdffddffdddddfff.......
.......fffffddfdf11fddddf.f.......
......ffffffddddf11ffddff.........
..........ffffddddddddddf.........
.........ffff4fddddddddf..........
...........f444ffdddddf4f.........
..........f8f44f8fffff8f4f........
.........f888f4f8888888f4f........
.........f888f44f888888f4f........
.........ff88f444ffffff44f........
........fddff.f444444444ff........
........fdddf.ffffffffffff........
........fddf..f888888888fdf.......
........f88f.ffffffffffffdf.......
.......f8888f444444f4444f88f......
.......fddddf444444f4444f8df......
.......fddfdf444444f44444fdf......
.......fddfff444444f44444fdf......
........ff.f4444444f44444ff.......
..........ff4444444f44444ff.......
..........f4444444ff44444ff.......
..........f444444f.f44444ff.......
..........f44444f..ffffff.........
.........fffffff...f8882f.........
.........f8288f....f8882f.........
........f55288f....f88552f........
........f8255f......f58882f.......
........f8288f.......ffffff.......
........ffffff....................
`;
            case "image2":
            case "goku0":return img`
..................................
..................................
..................................
..................................
.....................fffff........
...................fffff..........
..................fffff...........
.................ffffff...........
.................fffff..ffff......
...............fffffff.fffffff....
...............ffffffffffffffff...
...............fffffffffffffffff..
...............ffffffffffffffffff.
.............fffffffffffffffffffff
............ffffffffffffffffff....
...........fffffffffffffffff......
...........ffffffffffffffff.......
.......ffffffffffffffffffffff.....
.........ffffffffffdfffffffffff...
......fffffffffdfffdddffffffffff..
...ffffffffffffffffddddffffff.....
.....fffffffdffddffdddddfff.......
.......fffffddfdf11fddddf.f.......
......ffffffddddf11ffddff.........
..........ffffddddddddddf.........
.........ffff4fddddddddf..........
...........f444ffdddddf4f.........
.....f8.....f44f8fffff8f4f........
....f88.....8f4f8888888f4f........
....f88.....8f44f888888f4f........
....ff8.....8f444ffffff44f........
...fddf.....f.f444444444ff....df..
...fddd.....f.ffffffffffff....df..
...fddf.......f888888888f.....88f.
...f88f.......ffffffffffff....8df.
..f8888.......f4444f444444f...fdf.
..fdddd.......f4444f444444f...fdf.
..fddfd.......44444f444444f...ff..
..fddff.......44444f444444f...ff..
...ff.........44444f4444444f..ff..
.......f......44444f4444444f..ff..
..............44444ff4444444f.....
..............44444f.f444444f.....
..............ffffff..f44444f.....
..............f2888f...fffffff....
..............f2888f....f8828f....
.............f25588f....f88255f...
............f28885f......f5528f...
............ffffff.......f8828f...
.........................ffffff...
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
