// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "goku0":return img`
..................................
..................................
..................................
..................................
........fffff.....................
..........fffff...................
...........fffff..................
...........ffffff.................
......ffff..fffff.................
....fffffff.fffffff...............
...ffffffffffffffff...............
..fffffffffffffffff...............
.ffffffffffffffffff...............
fffffffffffffffffffff.............
....ffffffffffffffffff............
......fffffffffffffffff...........
.......ffffffffffffffff...........
.....ffffffffffffffffffffff.......
...fffffffffffdffffffffff.........
..ffffffffffdddfffdfffffffff......
.....ffffffddddffffffffffffffff...
.......fffdddddffddffdfffffff.....
.......f.fddddf11fdfddfffff.......
.........ffddff11fddddffffff......
.........fddddddddddffff..........
..........fddddddddf4ffff.........
.........f4fdddddff444f...........
........f4f8fffff8f44f8f..........
........f4f8888888f4f888f.........
........f4f888888f44f888f.........
........f44ffffff444f88ff.........
........ff444444444f.ffddf........
........ffffffffffff.fdddf........
.......fdf888888888f..fddf........
.......fdffffffffffff.f88f........
......f88f4444f444444f8888f.......
......fd8f4444f444444fddddf.......
......fdf44444f444444fdfddf.......
......fdf44444f444444fffddf.......
.......ff44444f4444444f.ff........
.......ff44444f4444444ff..........
.......ff44444ff4444444f..........
.......ff44444f.f444444f..........
.........ffffff..f44444f..........
.........f2888f...fffffff.........
.........f2888f....f8828f.........
........f25588f....f88255f........
.......f28885f......f5528f........
.......ffffff.......f8828f........
....................ffffff........
`;
            case "[NtOI*Pj4b,yaY/nf|P,":
            case "goku battle form":return img`
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..............................fffff...............
............................ff33f.................
...........................f33ff..................
..........................f33fff..................
..........................f33ff...fff.............
.........................f33fff..f333ff...........
.........................f33fff.f333333f..........
.........................f33ffff33333333f.........
.........................f33fff33333ffffff........
.......................ff33fff33333ffffffff.......
......................f333fffff33ffffff...........
.....................f333ffffffffffff.............
.....................f3fff3fffffffff..............
................fffff33ff33fffffff33fff...........
...................f33fff33ffdfffff3333ff.........
................fff33fffff3ffdddffffffffff........
.............fff3333fffffdf3fddddfffff............
...............fffffffdffddffdddddff..............
.................fffffddfdf11fddddfff.............
....................ffddddf11ffddf..f.............
....................fdffdddddddddf................
.....................ffffdddddddf.................
...................ffefddffddddff.................
..................feefefdddfffff.f................
..................f99ef4ffddddddf4f...............
.................f9889ee4fffdddf9ef...............
.................ff98894e4f9fff89ef...............
..............ff.fdf989444ef988894f...............
.............fedffddf9f4e44ef989eef....f..........
............fdfedfeddfe44fe4ef9f4fdf..f1ff........
...........fdedffdedeffee4fe44f4efddfffdedf.......
...........fdddef8ddf..feeefee4efddd98fedef.......
............fdede8def...fffff999fdd98fddedf.......
............fdd998ff....f8888888ffdf8fdddf........
.............fffff.....ffffff999f.fffffff.........
.......................feefe4fef4f................
......................feefe44fee4f................
......................feef444fe444f...............
......................fe4e444fe444f...............
.....................fe444444fe444f...............
.....................fee44e44fe444f...............
....................fefeee44feee44f...............
....................fe4ff444feee4ef...............
....................fe44444effeeef4f..............
...................fffeee44efefee44f..............
...................feeffeeefee4ff44f..............
...................feee44ffffe44444f..............
....................fffe44f.fee444f...............
...................f626fff..ffffff................
...................f6268f...f6662f................
..................f55255f...f5552f................
..................f6268f....f66662f...............
..................f6288f.....f66662f..............
..................fffff.......ffffff..............
`;
            case "image1":
            case "goku":return img`
..................fffff........
................fffff..........
...............fffff...........
..............ffffff...........
..............fffff..ffff......
............fffffff.fffffff....
............ffffffffffffffff...
............fffffffffffffffff..
............ffffffffffffffffff.
..........fffffffffffffffffffff
.........ffffffffffffffffff....
........fffffffffffffffff......
........ffffffffffffffff.......
....ffffffffffffffffffffff.....
......ffffffffffdfffffffffff...
...fffffffffdfffdddffffffffff..
ffffffffffffffffddddffffff.....
..fffffffdffddffdddddfff.......
....fffffddfdf11fddddf.f.......
...ffffffddddf11ffddff.........
.......ffffddddddddddf.........
......ffff4fddddddddf..........
........f444ffdddddf4f.........
.......f8f44f8fffff8f4f........
......f888f4f8888888f4f........
......f888f44f888888f4f........
......ff88f444ffffff44f........
.....fddff.f444444444ff........
.....fdddf.ffffffffffff........
.....fddf..f888888888fdf.......
.....f88f.ffffffffffffdf.......
....f8888f444444f4444f88f......
....fddddf444444f4444f8df......
....fddfdf444444f44444fdf......
....fddfff444444f44444fdf......
.....ff.f4444444f44444ff.......
.......ff4444444f44444ff.......
.......f4444444ff44444ff.......
.......f444444f.f44444ff.......
.......f44444f..ffffff.........
......fffffff...f8882f.........
......f8288f....f8882f.........
.....f55288f....f88552f........
.....f8255f......f58882f.......
.....f8288f.......ffffff.......
.....ffffff....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
