// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "goku":return img`
..................................
..................................
..................................
..................................
.....................fffff........
...................fffff..........
..................fffff...........
.................ffffff...........
.................fffff..ffff......
...............fffffff.fffffff....
...............ffffffffffffffff...
...............fffffffffffffffff..
...............ffffffffffffffffff.
.............fffffffffffffffffffff
............ffffffffffffffffff....
...........fffffffffffffffff......
...........ffffffffffffffff.......
.......ffffffffffffffffffffff.....
.........ffffffffffdfffffffffff...
......fffffffffdfffdddffffffffff..
...ffffffffffffffffddddffffff.....
.....fffffffdffddffdddddfff.......
.......fffffddfdf11fddddf.f.......
......ffffffddddf11ffddff.........
..........ffffddddddddddf.........
.........ffff4fddddddddf..........
...........f444ffdddddf4f.........
..........f8f44f8fffff8f4f........
.........f888f4f8888888f4f........
.........f888f44f888888f4f........
.........ff88f444ffffff44f........
........fddff.f444444444ff........
........fdddf.ffffffffffff........
........fddf..f888888888fdf.......
........f88f.ffffffffffffdf.......
.......f8888f444444f4444f88f......
.......fddddf444444f4444f8df......
.......fddfdf444444f44444fdf......
.......fddfff444444f44444fdf......
........ff.f4444444f44444ff.......
..........ff4444444f44444ff.......
..........f4444444ff44444ff.......
..........f444444f.f44444ff.......
..........f44444f..ffffff.........
.........fffffff...f8882f.........
.........f8288f....f8882f.........
........f55288f....f88552f........
........f8255f......f58882f.......
........f8288f.......ffffff.......
........ffffff....................
`;
            case "image2":
            case "goku0":return img`
..................................
..................................
..................................
..................................
........fffff.....................
..........fffff...................
...........fffff..................
...........ffffff.................
......ffff..fffff.................
....fffffff.fffffff...............
...ffffffffffffffff...............
..fffffffffffffffff...............
.ffffffffffffffffff...............
fffffffffffffffffffff.............
....ffffffffffffffffff............
......fffffffffffffffff...........
.......ffffffffffffffff...........
.....ffffffffffffffffffffff.......
...fffffffffffdffffffffff.........
..ffffffffffdddfffdfffffffff......
.....ffffffddddffffffffffffffff...
.......fffdddddffddffdfffffff.....
.......f.fddddf11fdfddfffff.......
.........ffddff11fddddffffff......
.........fddddddddddffff..........
..........fddddddddf4ffff.........
.........f4fdddddff444f...........
........f4f8fffff8f44f8f..........
........f4f8888888f4f888f.........
........f4f888888f44f888f.........
........f44ffffff444f88ff.........
........ff444444444f.ffddf........
........ffffffffffff.fdddf........
.......fdf888888888f..fddf........
.......fdffffffffffff.f88f........
......f88f4444f444444f8888f.......
......fd8f4444f444444fddddf.......
......fdf44444f444444fdfddf.......
......fdf44444f444444fffddf.......
.......ff44444f4444444f.ff........
.......ff44444f4444444ff..........
.......ff44444ff4444444f..........
.......ff44444f.f444444f..........
.........ffffff..f44444f..........
.........f2888f...fffffff.........
.........f2888f....f8828f.........
........f25588f....f88255f........
.......f28885f......f5528f........
.......ffffff.......f8828f........
....................ffffff........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
